server.port=8084
spring.application.name=cart-service
spring.data.redis.host=localhost
spring.data.redis.port=6379

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=when-authorized
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans

# Actuator & Prometheus
management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=when-authorized
# Zipkin tracing
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
